letter = "A".."G" | "a".."b";
Chord = "m" | "M" | "aug" | "dim";
digit  = "0".."9";
number = digit | digit, number;
blank = {" " | "\n" | "\t" | "\r"};

toneList = "[", blank, toneListContent, blank, "]" | "[]";
toneListContent = Tone | Tone, ",", blank, toneListContent;
noteList = "[" noteListContent "]" | "[]";
noteListContent = Note | Note, ",", blank, noteListContent;
noteOrChordList = "[", noteOrChordList, "]" | "[]";
noteOrChordListContent = (Note | RootedChord), [",", blank, noteOrChordList];

Interval = ["-"], number;

Melody = "[", Interval, "]";

RootedChord = letter, Chord;

Song = noteOrChordList;

Tone = letter, ["b" | "#"], digit;
Note = Tone, ":", Duration;
Duration = number, ["T" | "t"];